### ISSUE TITLE
Stuck in a loop where I got the yellow warning bar that something was wrong with FPN and the blue bar that said it was connected [v0.9]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#625] opened 2019-09-13 16:40 UTC
Via [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1568384897207100),

**Stephen Horlander 7:28 AM**
I’m not sure what caused it (and a restart fixed it) but this morning I was stuck in a loop where I got the yellow warning bar that something was wrong with FPN and the blue bar that said it was connected.

**Comment by stpeter** [comment] 2019-09-13 20:47
This might be a dupe of https://github.com/mozilla/secure-proxy/issues/569

**Comment by bakulf** [comment] 2019-09-13 22:57
Correct.

**Closed by bakulf** 2019-09-13 22:57 UTC
Labels: SLACK
