### ISSUE TITLE
"Unable to find the proxy server" with network down

### ISSUE THREAD

**Issue by hildjj** [mozilla/secure-proxy#618] opened 2019-09-12 22:57 UTC
Reproduce:

1. log in to FPN on a working network
2. disconnect computer from network
3. visit a site

Expected:
Error page I would normally get about the network being down.

Actual:
Error page saying: 
```
Unable to find the proxy server

Firefox is configured to use a proxy server that can’t be found.

    Check the proxy settings to make sure that they are correct.
    Check to make sure your computer has a working network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Nightly is permitted to access the Web.
```

Suggested approach:
For connection errors, show the underlying error instead of the proxy error.  Think about if there are any other errors that should receive this treatment.

**Comment by mayhemer** [comment] 2019-09-13 09:04
This is actually the correct error to show (expected, not a bug).  We were always showing "proxy host not found" when there was a proxy configured.

If want to show something else (or more) for secure-proxy, this add-on has to take care of it.

**Comment by bakulf** [comment] 2019-09-13 15:49
No needs at the moment. Let's close this bug.

**Closed by bakulf** 2019-09-13 15:49 UTC
