### ISSUE TITLE
[intermitent]Secure proxy is randomly disconnecting while browsing on Netflix

### ISSUE THREAD

**Issue by madalincm** [mozilla/secure-proxy#800] opened 2019-11-22 09:47 UTC
#### Affected Platforms:
-  Windows 10 (64-bit)
-  Mac 10.14.2

#### Affected versions:
- unsigned v16 build

#### Precondition:
Have SP build installed

#### Steps to reproduce
1. Turn on Secure Proxy
2. Open Netflix and perform any normal action (open a video, watch a video etc)

#### Expected result
- The secure proxy remains on

#### Actual result:
- Secure proxy is disconnected the generic error message is displayed inside the doorhanger:

Please view the screenrecording here:
https://drive.google.com/open?id=1mx2xjtIJ-R-xWW_LTwFf6ben7249O5xq

**Comment by bakulf** [comment] 2019-11-22 15:11
When the proxy is on, Cloudflare returns HTTP status code 407 to some of the requests, randomly even if the JWT is valid and correctly included in the Proxy-Authorization header.

We are reasonably convinced that the issue is on the Cloudflare side. Here is why:

1. the same JWT is used for other requests which success results (HTTP status code 200 or similar)
2. the JWT is not expired - expiration time is 5 hours in the future in our tests.
3. executing the same request with the same JWT, we obtain an HTTP status code 200 (or similar).

I have the browser log of the http requests done when the proxy is on.
Here is one of the most significant parts:

```
2019-11-22 11:06:34.581 ⁃ nsHttpChannel ⁃ 7f962cb6d000 ⁃ released ⁃ status=0 ⁃ http-status=101 ⁃ url=https://push.prod.netflix.com/ws
2019-11-22 11:06:44.967 ⁃ nsHttpChannel ⁃ 7f962c21d000 ⁃ released ⁃ status=0 ⁃ http-status=101 ⁃ url=https://push.prod.netflix.com/ws
2019-11-22 11:06:49.212 ⁃ nsHttpChannel ⁃ 7f962e4e9000 ⁃ released ⁃ status=0 ⁃ http-status=101 ⁃ url=https://push.prod.netflix.com/ws
2019-11-22 11:06:56.329 ⁃ nsHttpChannel ⁃ 7f962cf29000 ⁃ released ⁃ status=0 ⁃ http-status=101 ⁃ url=https://push.prod.netflix.com/ws
2019-11-22 11:07:04.343 ⁃ nsHttpChannel ⁃ 7f962ccd5000 ⁃ released ⁃ status=0 ⁃ http-status=101 ⁃ url=https://push.prod.netflix.com/ws
2019-11-22 11:07:14.336 ⁃ nsHttpChannel ⁃ 7f962ec27000 ⁃ released ⁃ status=804b0197 ⁃ http-status=407 ⁃ url=https://push.prod.netflix.com/ws
2019-11-22 11:07:18.373 ⁃ nsHttpChannel ⁃ 7f962fb30000 ⁃ released ⁃ status=0 ⁃ http-status=101 ⁃ url=https://push.prod.netflix.com/ws
```

As you can see there are a few similar requests to https://push.prod.netflix.com/ws running between 11.06 and 11.07. 5 of them succeed, 1 fails, the next one succeeds again, using the same JWT.

The failing one contains this request (the proxy-authorization header value is not printed in our logs):

```
2019-11-22 11:07:14.405028 UTC - [Parent 30556: Socket Thread]: V/nsHttp nsHttpConnection::MakeConnectString for transaction=0x7f962cc9b000 [
2019-11-22 11:07:14.405032 UTC - [Parent 30556: Socket Thread]: E/nsHttp   CONNECT push.prod.netflix.com:443 HTTP/1.1
2019-11-22 11:07:14.405034 UTC - [Parent 30556: Socket Thread]: E/nsHttp   User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0
2019-11-22 11:07:14.405036 UTC - [Parent 30556: Socket Thread]: E/nsHttp   Proxy-Connection: keep-alive
2019-11-22 11:07:14.405038 UTC - [Parent 30556: Socket Thread]: E/nsHttp   Connection: keep-alive
2019-11-22 11:07:14.405040 UTC - [Parent 30556: Socket Thread]: E/nsHttp   Host: push.prod.netflix.com:443
2019-11-22 11:07:14.405043 UTC - [Parent 30556: Socket Thread]: E/nsHttp   Proxy-Authorization: **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
2019-11-22 11:07:14.405045 UTC - [Parent 30556: Socket Thread]: V/nsHttp 
```

This is the result:

```
2019-11-22 11:07:14.452938 UTC - [Parent 30556: Socket Thread]: I/nsHttp http response [
  HTTP/1.1 407 Proxy Authentication Required
  Cf-Warp-Error: 1
  Proxy-Authenticate: Bearer realm="Cloudflare Warp for Firefox"
  Date: Fri, 22 Nov 2019 11:07:14 GMT
  Content-Length: 3
  Content-Type: text/plain; charset=utf-8
    OriginalHeaders
  Cf-Warp-Error: 1
  Proxy-Authenticate: Bearer realm="Cloudflare Warp for Firefox"
  Date: Fri, 22 Nov 2019 11:07:14 GMT
  Content-Length: 3
  Content-Type: text/plain; charset=utf-8
```

**Comment by aplunk** [comment] 2019-11-22 20:31
The issue has been addressed. @bakulf reassign to me if you see any other issues.

**Comment by bakulf** [comment] 2019-11-23 07:33
@aplunk great work! thanks!

**Closed by bakulf** 2019-11-23 07:33 UTC
Labels: [QA]:Major issue, bug

**Comment by madalincm** [comment] 2019-11-25 15:27
I have verified this issue using the the v16 and v17 versions of Secure proxy and I'm not able to reproduce this issue.
Marking bug as verified fixed,
