### ISSUE TITLE
v15 users do not remain with the unlimited version of SP after updating to v17

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#816] opened 2019-11-27 13:33 UTC
#### Affected Platforms:
- Windows 10 (64-bit)
- Mac 10.14.2
- Linux Ubuntu 19.04

#### Affected versions:
- signed v15 build
- signed v17 build (used for updating)

#### Steps to reproduce
1. Install SP v15 and create an account.
2. Update to SP v17 and restart the browser.
3. Wait for the login token to expire. 

#### Expected result
- After the login token expires and a new one is generated the user remains with the unlimited version of SP.

#### Actual result:
- After the login token expires and a new one is generated the user is switched to the limited version of SP.

#### Notes:
- If SP is not running and you wait for the token to expire it appears as you still have the unlimited version of SP, but when enabling SP the interface switches to the limited version and your first pass starts.

![1](https://user-images.githubusercontent.com/17178945/69729483-10ba4780-112f-11ea-95cf-e0ffcd173df9.gif)

**Comment by johngruen** [comment] 2019-11-27 15:07
@bakulf do you think this is extension related or service related?

**Comment by bakulf** [comment] 2019-11-27 15:47
It's not a bug. What is happening here is:

1. SP is configured to use a post-3rd of december backend.
2. the user installs v15 and SP goes in free-tier mode. But v15 doesn't implement the passes UI and the countdown. The first pass is consumed but no countdown is shown.
3. v17 is installed. The passes are shown correctly.

Note that:
a. if the user installs v15 before the 3rd of December, they will be considered a beta user and they will be unlimited with v17.
b. if the user uses v15 after the 3rd of December, they will be in auto-renew mode and they will consume all the passes. After that, an error will be shown.

**Closed by bakulf** 2019-11-27 15:47 UTC
Labels: [QA]:Blocker issue, bug

**Comment by bsurd** [comment] 2019-11-28 15:36
Confirmed with baku and he helped me to test that users pre-3rd remain with the unlimited version. Marking this as invalid.
